Repository naoufelmhadhbi/timesheet-devops, pull requests merged in 2022-01, with the labels that each got.

#1 Add remaining entities
  .gitignore
  src/main/java/tn/esprit/spring/entities/Contrat.java
  src/main/java/tn/esprit/spring/entities/Departement.java
  src/main/java/tn/esprit/spring/entities/Employe.java
  src/main/java/tn/esprit/spring/entities/Entreprise.java
Labels: enhancement

#5 add entreprise entity
  src/main/java/tn/esprit/spring/controller/EntrepriseRestController.java
  src/main/java/tn/esprit/spring/repository/EntrepriseRepository.java
  src/main/java/tn/esprit/spring/services/EntrepriseServiceImpl.java
  src/main/java/tn/esprit/spring/services/IEntrepriseService.java
  src/test/java/tn/esprit/spring/services/EntrepriseServiceImplTest.java
Labels: enhancement

#4 Add pipeline jenkinsfiles
  pipelines/CD-jenkinsfile
  pipelines/CI-jenkinsfile
Labels: Pipelines

#7 Add Employe feature
  src/main/java/tn/esprit/spring/controller/EmployeRestController.java
  src/main/java/tn/esprit/spring/entities/Employe.java
  src/main/java/tn/esprit/spring/repository/EmployeRepository.java
  src/main/java/tn/esprit/spring/services/EmployeServiceImpl.java
  src/main/java/tn/esprit/spring/services/IEmployeService.java
  src/test/java/tn/esprit/spring/services/EmployeServiceImplTest.java
Labels: enhancement

#9 Fix Entreprise entity failing tests
  src/main/java/tn/esprit/spring/entities/Entreprise.java
  src/main/java/tn/esprit/spring/repository/EntrepriseRepository.java
  src/main/java/tn/esprit/spring/services/EntrepriseServiceImpl.java
  src/main/java/tn/esprit/spring/services/IEntrepriseService.java
  src/test/java/tn/esprit/spring/services/EntrepriseServiceImplTest.java
Labels: bug
